### ISSUE TITLE
feature request: add the new keys values down the tree

### ISSUE THREAD

**Issue by zakidze** [vordgi/nimpl-inio#84] opened 2024-06-20 16:46 UTC
example when i have a json with missing value in certain locale and i use inio to add the missing value

inio adds the missing value + key to the end

reason : when use gitadd  and commit only new keys would be shown or added stuff

**Comment by vordgi** [comment] 2024-06-20 17:04
What if u had:
```json
{
  "example": {
    "key1": "value1"
  },
  "example2": {
    "key2": "value2"
  }
}
```
And add new key "example.key3"?

And git should always show changes only, no matter where they are

**Comment by zakidze** [comment] 2024-06-20 17:06
i see that git example delete everything than add everything

**Comment by zakidze** [comment] 2024-06-20 17:09
![Screenshot_20240620_180844_Chrome](https://github.com/vordgi/nimpl-inio/assets/61497110/2b57d999-6c8a-4572-8960-1d65a1aa860a)


![Screenshot_20240620_180834_Chrome](https://github.com/vordgi/nimpl-inio/assets/61497110/14d3834a-dc2b-46c7-bed5-a7f3b2daf473)

**Comment by zakidze** [comment] 2024-06-20 17:10
look even if 1 line is change git delete everything and adds everything

**Comment by zakidze** [comment] 2024-06-20 17:10
this make the review hard to get the changes

**Comment by zakidze** [comment] 2024-06-20 17:13
yes

**Comment by zakidze** [comment] 2024-06-20 17:13
i use prettier

**Comment by vordgi** [comment] 2024-06-20 17:17
The problem is that sometimes it format your code, sometimes its not. You can use husky and format it each tome on precommit.

From my side I will think about inio format style

**Comment by zakidze** [comment] 2024-06-20 17:20
so there is some incostincies between inio styles and inio styles

**Comment by vordgi** [comment] 2024-06-20 17:24
Between inio formatting and prettier formatting*

And it is logical. Inio have no idea about your formatters and linters (_and shouln't_)

**Comment by zakidze** [comment] 2024-06-20 17:28
whar you propose souloution for this

**Comment by vordgi** [comment] 2024-06-20 17:31
For now - "You can use husky and format it each time on precommit" [by prettier to keep the same codestyle which declared in prettier rules]

But I will think in additional

**Comment by vordgi** [comment] 2024-06-30 18:39
Closing this task because the problem is not in this (_and this cannot be done for reasons described above_).

Opened a task on indent style rules - #98

**Closed by vordgi** 2024-06-30 18:39 UTC

**Comment by zakidze** [comment] 2024-06-30 18:44
you know better 

PS: the adviece you told me about worked well  i mean husky with prettier formating 

at least reduced 6000 lines to 600 lines

**Comment by zakidze** [comment] 2024-06-30 18:46
hope you tackle the search missing value on all project issue or , repititive keys issue

**Comment by vordgi** [comment] 2024-06-30 20:00
I keep them in mind, looking for a suitable solution

**Comment by zakidze** [comment] 2024-06-30 20:04
at least make a i18n dir like scan by dir

**Comment by vordgi** [comment] 2024-06-30 21:27
Indent rules shipped. Configure it just like your prettier rules.

`inio.config.js`
```js
module.exports = {
    indent: {
        size: 1,
        type: "tab",
    },
};
```
